# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('icon', models.CharField(max_length=100)),
                ('song', models.CharField(max_length=100)),
            ],
        ),
    ]
