# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markermodel',
            name='icon',
        ),
    ]
